### ISSUE TITLE
Import Export Plugin IP4.x  and Data Export Plgin IP3.x

### ISSUE THREAD

**Issue by alaneku** [impresspages-plugins/ImportExport#1]
When using the Data Export Plugin for IP3.x, it appears that the plugiin does not collect images. After unzipping the archive zip file produced by the plugin  the  archive/file directory is empty.

On importing the zip using  the IP4.x ImportExport  plugin a series of error messages such as  
"File does not exist /var/www/ip41/file/secure/tmp/archive_2014_06_15_0931/archive/file/euFlag200.png"

There appears to be one error message for every image on the #.x site.

**Comment by maskas** [comment]
Going to have a look

**Comment by maskas** [comment]
I've fixed file permissions issue related to files. Could you please check if that helped? https://github.com/impresspages-plugins/ImportExport/commit/47b8bd3765c977beb2079a120b30562d953438fb

**Comment by alaneku** [comment]
hi
It seems that pictures and text import ok now, many thanks.  Images are much larger than on the ip3.9 site, but that must be a function of the layout of the IP4 theme, I am using Air which is much wider.

I will work at modifying the theme to make more like my IP3.x site.

Many thanks that is a lot of progress today, I must spend time trying to understand the whole situation of importing more.

Alan
