### ISSUE TITLE
[object Object] Javascript alert while export

### ISSUE THREAD

**Issue by y0s3ph** [impresspages-plugins/ImportExport#4]
![screen shot 2015-05-27 at 12 32 52](https://cloud.githubusercontent.com/assets/11368223/7834120/9b8c6944-046c-11e5-9f4d-46a6bea0faf1.png)

When I export, after a minutes, I have this issue.
I tried with Chrome, Firefox and Safari.

It's a error with any of my own modules?
Can I see the error in detail?

**Comment by jankus** [comment]
You should open Developer Tools in your browser and check for the real issues. Maybe there are errors or your server returns something that JavaScript doesn't expect.

**Comment by y0s3ph** [comment]
![screen shot 2015-05-27 at 14 26 40](https://cloud.githubusercontent.com/assets/11368223/7835906/9f315202-047c-11e5-8795-9a6d9b6c5787.png)
I'm using MAMP 3.2.1 
Apache/2.2.29 (Unix)
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
PHP extension: mysqli
PHP version: 5.6.7

**Comment by jankus** [comment]
This error only says that something bad happened in the server and it crashed. And it doesn't give any details why.
